CREATE TABLE IF NOT EXISTS accounts (
  access_email TEXT PRIMARY KEY NOT NULL,
  eight_email TEXT,
  eight_user_id TEXT,
  access_token TEXT,
  refresh_token TEXT,
  token_expires_at INTEGER,
  bedtime TEXT NOT NULL DEFAULT '23:00',
  wake_time TEXT NOT NULL DEFAULT '06:00',
  timezone TEXT NOT NULL DEFAULT 'America/Los_Angeles',
  early_level INTEGER NOT NULL DEFAULT 0,
  middle_level INTEGER NOT NULL DEFAULT 0,
  late_level INTEGER NOT NULL DEFAULT 0,
  settings_saved INTEGER NOT NULL DEFAULT 0,
  paused INTEGER NOT NULL DEFAULT 0,
  cycle_id TEXT,
  last_commanded_level INTEGER,
  last_command_known INTEGER NOT NULL DEFAULT 0,
  manual_override INTEGER NOT NULL DEFAULT 0,
  override_level INTEGER,
  last_run_at TEXT,
  last_error TEXT
);
